version: '3'
services:
  cli:
    build: .
    env_file:
      - .env
    environment:
      - XDG_DATA_HOME=/app/data
    volumes:
      - signal-cli:/app/data/signal-cli
      - ./signal_scanner_bot:/app/signal_scanner_bot
    restart: unless-stopped
volumes:
  signal-cli:
