version: '3'
services:
  cli:
    build: .
    env_file:
      - .env
    environment:
      - XDG_DATA_HOME=/app/data
    volumes:
      - signal-cli:/app/data/signal-cli
      - .:/app
    restart: always
volumes:
  signal-cli:
