name: Lint and Test

on: pull_request

jobs:

  format:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout repo
        uses: actions/checkout@v2
      -
        name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      -
        name: Install Dependencies
        run: pip install black
      -
        name: Check formatting with black
        run: black --check .

  lint:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout repo
        uses: actions/checkout@v2
      -
        name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      -
        name: Install Dependencies
        run: pip install flake8
      -
        name: Lint with flake8
        run: flake8 .

  types:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout repo
        uses: actions/checkout@v2
      -
        name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      -
        name: Install Dependencies
        run: pip install mypy
      -
        name: Check typing with mypy
        run: mypy .

  test:
    runs-on: ubuntu-latest
    # Tests are expensive to run, don't run them unless the other checks pass
    needs: [format, lint, types]

    steps:
      -
        name: Checkout repo
        uses: actions/checkout@v2
      -
        name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      -
        name: Install Dependencies
        run: pip install pytest pytest-cov
      -
        name: Test with pytest
        run: pytest --cov .

  build:
    runs-on: ubuntu-latest
    # Builds are expensive to run, don't run them unless the other checks pass
    needs: [format, lint, types]

    steps:
      -
        uses: actions/checkout@v2
        name: Set up QEMU
      -
        uses: docker/setup-qemu-action@v1
        name: Set up Docker Buildx
      -
        uses: docker/setup-buildx-action@v1
        name: Login to DockerHub
      -
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            mpuckett259/signal-scanner-bot:latest
