name: Lint and Test

on: pull_request

jobs:

  static-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: pip install pre-commit
      - name: Run static checks
        run: pre-commit run --all-files

  test:
    runs-on: ubuntu-latest
    # Tests are expensive to run, don't run them unless the other checks pass
    needs: [static-checks]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: pip install pytest pytest-cov
      - name: Test with pytest
        run: pytest --cov .

  build:
    runs-on: ubuntu-latest
    needs:
      - static-checks
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - name: Build image
        run: just build
